/*
 * This file is generated by jOOQ.
 */
package database.tables.records;


import database.tables.AclClass;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclClassRecord extends UpdatableRecordImpl<AclClassRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -2045320365;

    /**
     * Setter for <code>public.acl_class.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_class.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_class.class</code>.
     */
    public void setClass_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_class.class</code>.
     */
    public String getClass_() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AclClass.ACL_CLASS.ID;
    }

    @Override
    public Field<String> field2() {
        return AclClass.ACL_CLASS.CLASS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getClass_();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getClass_();
    }

    @Override
    public AclClassRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AclClassRecord value2(String value) {
        setClass_(value);
        return this;
    }

    @Override
    public AclClassRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclClassRecord
     */
    public AclClassRecord() {
        super(AclClass.ACL_CLASS);
    }

    /**
     * Create a detached, initialised AclClassRecord
     */
    public AclClassRecord(Long id, String class_) {
        super(AclClass.ACL_CLASS);

        set(0, id);
        set(1, class_);
    }
}
