/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.AclClass;
import database.tables.AclEntry;
import database.tables.AclObjectIdentity;
import database.tables.AclSid;
import database.tables.ResourceParameters;
import database.tables.ResourceRelations;
import database.tables.ResourceTemplates;
import database.tables.Roles;
import database.tables.S3bucketTest;
import database.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACL_CLASS_PKEY = Indexes0.ACL_CLASS_PKEY;
    public static final Index UNIQUE_UK_2 = Indexes0.UNIQUE_UK_2;
    public static final Index ACL_ENTRY_PKEY = Indexes0.ACL_ENTRY_PKEY;
    public static final Index UNIQUE_UK_4 = Indexes0.UNIQUE_UK_4;
    public static final Index ACL_OBJECT_IDENTITY_PKEY = Indexes0.ACL_OBJECT_IDENTITY_PKEY;
    public static final Index UNIQUE_UK_3 = Indexes0.UNIQUE_UK_3;
    public static final Index ACL_SID_PKEY = Indexes0.ACL_SID_PKEY;
    public static final Index UNIQUE_UK_1 = Indexes0.UNIQUE_UK_1;
    public static final Index RESOURCE_PARAMETERS_PKEY = Indexes0.RESOURCE_PARAMETERS_PKEY;
    public static final Index RESOURCE_RELATIONS_PKEY = Indexes0.RESOURCE_RELATIONS_PKEY;
    public static final Index RESOURCE_TEMPLATES_PKEY = Indexes0.RESOURCE_TEMPLATES_PKEY;
    public static final Index UK_1XX1119BT1OJGJS2LFRYL5PCR = Indexes0.UK_1XX1119BT1OJGJS2LFRYL5PCR;
    public static final Index ROLES_PKEY = Indexes0.ROLES_PKEY;
    public static final Index UNIQUE_UK_5 = Indexes0.UNIQUE_UK_5;
    public static final Index S3BUCKET_TEST_PKEY = Indexes0.S3BUCKET_TEST_PKEY;
    public static final Index UK_6DOTKOTT2KJSP8VW4D0M25FB7 = Indexes0.UK_6DOTKOTT2KJSP8VW4D0M25FB7;
    public static final Index UK_DU5V5SR43G5BFNJI4VB8HG5S3 = Indexes0.UK_DU5V5SR43G5BFNJI4VB8HG5S3;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACL_CLASS_PKEY = Internal.createIndex("acl_class_pkey", AclClass.ACL_CLASS, new OrderField[] { AclClass.ACL_CLASS.ID }, true);
        public static Index UNIQUE_UK_2 = Internal.createIndex("unique_uk_2", AclClass.ACL_CLASS, new OrderField[] { AclClass.ACL_CLASS.CLASS }, true);
        public static Index ACL_ENTRY_PKEY = Internal.createIndex("acl_entry_pkey", AclEntry.ACL_ENTRY, new OrderField[] { AclEntry.ACL_ENTRY.ID }, true);
        public static Index UNIQUE_UK_4 = Internal.createIndex("unique_uk_4", AclEntry.ACL_ENTRY, new OrderField[] { AclEntry.ACL_ENTRY.ACL_OBJECT_IDENTITY, AclEntry.ACL_ENTRY.ACE_ORDER }, true);
        public static Index ACL_OBJECT_IDENTITY_PKEY = Internal.createIndex("acl_object_identity_pkey", AclObjectIdentity.ACL_OBJECT_IDENTITY, new OrderField[] { AclObjectIdentity.ACL_OBJECT_IDENTITY.ID }, true);
        public static Index UNIQUE_UK_3 = Internal.createIndex("unique_uk_3", AclObjectIdentity.ACL_OBJECT_IDENTITY, new OrderField[] { AclObjectIdentity.ACL_OBJECT_IDENTITY.OBJECT_ID_CLASS, AclObjectIdentity.ACL_OBJECT_IDENTITY.OBJECT_ID_IDENTITY }, true);
        public static Index ACL_SID_PKEY = Internal.createIndex("acl_sid_pkey", AclSid.ACL_SID, new OrderField[] { AclSid.ACL_SID.ID }, true);
        public static Index UNIQUE_UK_1 = Internal.createIndex("unique_uk_1", AclSid.ACL_SID, new OrderField[] { AclSid.ACL_SID.SID, AclSid.ACL_SID.PRINCIPAL }, true);
        public static Index RESOURCE_PARAMETERS_PKEY = Internal.createIndex("resource_parameters_pkey", ResourceParameters.RESOURCE_PARAMETERS, new OrderField[] { ResourceParameters.RESOURCE_PARAMETERS.ID }, true);
        public static Index RESOURCE_RELATIONS_PKEY = Internal.createIndex("resource_relations_pkey", ResourceRelations.RESOURCE_RELATIONS, new OrderField[] { ResourceRelations.RESOURCE_RELATIONS.ID }, true);
        public static Index RESOURCE_TEMPLATES_PKEY = Internal.createIndex("resource_templates_pkey", ResourceTemplates.RESOURCE_TEMPLATES, new OrderField[] { ResourceTemplates.RESOURCE_TEMPLATES.ID }, true);
        public static Index UK_1XX1119BT1OJGJS2LFRYL5PCR = Internal.createIndex("uk_1xx1119bt1ojgjs2lfryl5pcr", ResourceTemplates.RESOURCE_TEMPLATES, new OrderField[] { ResourceTemplates.RESOURCE_TEMPLATES.NAME }, true);
        public static Index ROLES_PKEY = Internal.createIndex("roles_pkey", Roles.ROLES, new OrderField[] { Roles.ROLES.ID }, true);
        public static Index UNIQUE_UK_5 = Internal.createIndex("unique_uk_5", Roles.ROLES, new OrderField[] { Roles.ROLES.NAME }, true);
        public static Index S3BUCKET_TEST_PKEY = Internal.createIndex("s3bucket_test_pkey", S3bucketTest.S3BUCKET_TEST, new OrderField[] { S3bucketTest.S3BUCKET_TEST.ID }, true);
        public static Index UK_6DOTKOTT2KJSP8VW4D0M25FB7 = Internal.createIndex("uk_6dotkott2kjsp8vw4d0m25fb7", Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
        public static Index UK_DU5V5SR43G5BFNJI4VB8HG5S3 = Internal.createIndex("uk_du5v5sr43g5bfnji4vb8hg5s3", Users.USERS, new OrderField[] { Users.USERS.PHONE }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
