/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.AclClass;
import database.tables.AclEntry;
import database.tables.AclObjectIdentity;
import database.tables.AclSid;
import database.tables.ResourceParameters;
import database.tables.ResourceRelations;
import database.tables.ResourceTemplates;
import database.tables.Roles;
import database.tables.S3bucketTest;
import database.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.acl_class</code>.
     */
    public static final AclClass ACL_CLASS = AclClass.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public static final AclEntry ACL_ENTRY = AclEntry.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public static final AclObjectIdentity ACL_OBJECT_IDENTITY = AclObjectIdentity.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public static final AclSid ACL_SID = AclSid.ACL_SID;

    /**
     * The table <code>public.resource_parameters</code>.
     */
    public static final ResourceParameters RESOURCE_PARAMETERS = ResourceParameters.RESOURCE_PARAMETERS;

    /**
     * The table <code>public.resource_relations</code>.
     */
    public static final ResourceRelations RESOURCE_RELATIONS = ResourceRelations.RESOURCE_RELATIONS;

    /**
     * The table <code>public.resource_templates</code>.
     */
    public static final ResourceTemplates RESOURCE_TEMPLATES = ResourceTemplates.RESOURCE_TEMPLATES;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.s3bucket_test</code>.
     */
    public static final S3bucketTest S3BUCKET_TEST = S3bucketTest.S3BUCKET_TEST;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
