/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables;


import com.softserve.rms.jooq.Indexes;
import com.softserve.rms.jooq.Keys;
import com.softserve.rms.jooq.Public;
import com.softserve.rms.jooq.tables.records.AclClassRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclClass extends TableImpl<AclClassRecord> {

    private static final long serialVersionUID = -1930891997;

    /**
     * The reference instance of <code>public.acl_class</code>
     */
    public static final AclClass ACL_CLASS = new AclClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclClassRecord> getRecordType() {
        return AclClassRecord.class;
    }

    /**
     * The column <code>public.acl_class.id</code>.
     */
    public final TableField<AclClassRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('acl_class_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.acl_class.class</code>.
     */
    public final TableField<AclClassRecord, String> CLASS = createField(DSL.name("class"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>public.acl_class</code> table reference
     */
    public AclClass() {
        this(DSL.name("acl_class"), null);
    }

    /**
     * Create an aliased <code>public.acl_class</code> table reference
     */
    public AclClass(String alias) {
        this(DSL.name(alias), ACL_CLASS);
    }

    /**
     * Create an aliased <code>public.acl_class</code> table reference
     */
    public AclClass(Name alias) {
        this(alias, ACL_CLASS);
    }

    private AclClass(Name alias, Table<AclClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private AclClass(Name alias, Table<AclClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AclClass(Table<O> child, ForeignKey<O, AclClassRecord> key) {
        super(child, key, ACL_CLASS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACL_CLASS_PKEY, Indexes.UNIQUE_UK_2);
    }

    @Override
    public Identity<AclClassRecord, Long> getIdentity() {
        return Keys.IDENTITY_ACL_CLASS;
    }

    @Override
    public UniqueKey<AclClassRecord> getPrimaryKey() {
        return Keys.ACL_CLASS_PKEY;
    }

    @Override
    public List<UniqueKey<AclClassRecord>> getKeys() {
        return Arrays.<UniqueKey<AclClassRecord>>asList(Keys.ACL_CLASS_PKEY, Keys.UNIQUE_UK_2);
    }

    @Override
    public AclClass as(String alias) {
        return new AclClass(DSL.name(alias), this);
    }

    @Override
    public AclClass as(Name alias) {
        return new AclClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AclClass rename(String name) {
        return new AclClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclClass rename(Name name) {
        return new AclClass(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
