/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.records;


import com.softserve.rms.jooq.tables.AclSid;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclSidRecord extends UpdatableRecordImpl<AclSidRecord> implements Record3<Long, Boolean, String> {

    private static final long serialVersionUID = -42549522;

    /**
     * Setter for <code>public.acl_sid.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_sid.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_sid.principal</code>.
     */
    public void setPrincipal(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_sid.principal</code>.
     */
    public Boolean getPrincipal() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.acl_sid.sid</code>.
     */
    public void setSid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.acl_sid.sid</code>.
     */
    public String getSid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Boolean, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Boolean, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AclSid.ACL_SID.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return AclSid.ACL_SID.PRINCIPAL;
    }

    @Override
    public Field<String> field3() {
        return AclSid.ACL_SID.SID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getPrincipal();
    }

    @Override
    public String component3() {
        return getSid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getPrincipal();
    }

    @Override
    public String value3() {
        return getSid();
    }

    @Override
    public AclSidRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AclSidRecord value2(Boolean value) {
        setPrincipal(value);
        return this;
    }

    @Override
    public AclSidRecord value3(String value) {
        setSid(value);
        return this;
    }

    @Override
    public AclSidRecord values(Long value1, Boolean value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclSidRecord
     */
    public AclSidRecord() {
        super(AclSid.ACL_SID);
    }

    /**
     * Create a detached, initialised AclSidRecord
     */
    public AclSidRecord(Long id, Boolean principal, String sid) {
        super(AclSid.ACL_SID);

        set(0, id);
        set(1, principal);
        set(2, sid);
    }
}
