/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.records;


import com.softserve.rms.jooq.tables.ResourceParameters;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceParametersRecord extends UpdatableRecordImpl<ResourceParametersRecord> implements Record6<Long, String, String, String, String, Long> {

    private static final long serialVersionUID = 357335012;

    /**
     * Setter for <code>public.resource_parameters.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.resource_parameters.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.resource_parameters.column_name</code>.
     */
    public void setColumnName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.resource_parameters.column_name</code>.
     */
    public String getColumnName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.resource_parameters.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.resource_parameters.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.resource_parameters.field_type</code>.
     */
    public void setFieldType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.resource_parameters.field_type</code>.
     */
    public String getFieldType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.resource_parameters.pattern</code>.
     */
    public void setPattern(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.resource_parameters.pattern</code>.
     */
    public String getPattern() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.resource_parameters.resource_template_id</code>.
     */
    public void setResourceTemplateId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.resource_parameters.resource_template_id</code>.
     */
    public Long getResourceTemplateId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ResourceParameters.RESOURCE_PARAMETERS.ID;
    }

    @Override
    public Field<String> field2() {
        return ResourceParameters.RESOURCE_PARAMETERS.COLUMN_NAME;
    }

    @Override
    public Field<String> field3() {
        return ResourceParameters.RESOURCE_PARAMETERS.NAME;
    }

    @Override
    public Field<String> field4() {
        return ResourceParameters.RESOURCE_PARAMETERS.FIELD_TYPE;
    }

    @Override
    public Field<String> field5() {
        return ResourceParameters.RESOURCE_PARAMETERS.PATTERN;
    }

    @Override
    public Field<Long> field6() {
        return ResourceParameters.RESOURCE_PARAMETERS.RESOURCE_TEMPLATE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getColumnName();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getFieldType();
    }

    @Override
    public String component5() {
        return getPattern();
    }

    @Override
    public Long component6() {
        return getResourceTemplateId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getColumnName();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getFieldType();
    }

    @Override
    public String value5() {
        return getPattern();
    }

    @Override
    public Long value6() {
        return getResourceTemplateId();
    }

    @Override
    public ResourceParametersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ResourceParametersRecord value2(String value) {
        setColumnName(value);
        return this;
    }

    @Override
    public ResourceParametersRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ResourceParametersRecord value4(String value) {
        setFieldType(value);
        return this;
    }

    @Override
    public ResourceParametersRecord value5(String value) {
        setPattern(value);
        return this;
    }

    @Override
    public ResourceParametersRecord value6(Long value) {
        setResourceTemplateId(value);
        return this;
    }

    @Override
    public ResourceParametersRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourceParametersRecord
     */
    public ResourceParametersRecord() {
        super(ResourceParameters.RESOURCE_PARAMETERS);
    }

    /**
     * Create a detached, initialised ResourceParametersRecord
     */
    public ResourceParametersRecord(Long id, String columnName, String name, String fieldType, String pattern, Long resourceTemplateId) {
        super(ResourceParameters.RESOURCE_PARAMETERS);

        set(0, id);
        set(1, columnName);
        set(2, name);
        set(3, fieldType);
        set(4, pattern);
        set(5, resourceTemplateId);
    }
}
