/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.records;


import com.softserve.rms.jooq.tables.ResourceRelations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceRelationsRecord extends UpdatableRecordImpl<ResourceRelationsRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 901094658;

    /**
     * Setter for <code>public.resource_relations.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.resource_relations.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.resource_relations.related_resource_template_id</code>.
     */
    public void setRelatedResourceTemplateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.resource_relations.related_resource_template_id</code>.
     */
    public Long getRelatedResourceTemplateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.resource_relations.resource_parameter_id</code>.
     */
    public void setResourceParameterId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.resource_relations.resource_parameter_id</code>.
     */
    public Long getResourceParameterId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ResourceRelations.RESOURCE_RELATIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return ResourceRelations.RESOURCE_RELATIONS.RELATED_RESOURCE_TEMPLATE_ID;
    }

    @Override
    public Field<Long> field3() {
        return ResourceRelations.RESOURCE_RELATIONS.RESOURCE_PARAMETER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRelatedResourceTemplateId();
    }

    @Override
    public Long component3() {
        return getResourceParameterId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRelatedResourceTemplateId();
    }

    @Override
    public Long value3() {
        return getResourceParameterId();
    }

    @Override
    public ResourceRelationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ResourceRelationsRecord value2(Long value) {
        setRelatedResourceTemplateId(value);
        return this;
    }

    @Override
    public ResourceRelationsRecord value3(Long value) {
        setResourceParameterId(value);
        return this;
    }

    @Override
    public ResourceRelationsRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourceRelationsRecord
     */
    public ResourceRelationsRecord() {
        super(ResourceRelations.RESOURCE_RELATIONS);
    }

    /**
     * Create a detached, initialised ResourceRelationsRecord
     */
    public ResourceRelationsRecord(Long id, Long relatedResourceTemplateId, Long resourceParameterId) {
        super(ResourceRelations.RESOURCE_RELATIONS);

        set(0, id);
        set(1, relatedResourceTemplateId);
        set(2, resourceParameterId);
    }
}
