/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.records;


import com.softserve.rms.jooq.tables.Tables;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesRecord extends UpdatableRecordImpl<TablesRecord> implements Record7<Long, String, String, Long, Long, Integer, String> {

    private static final long serialVersionUID = -1854613717;

    /**
     * Setter for <code>public.tables.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tables.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tables.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tables.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tables.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tables.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tables.resource_template_id</code>.
     */
    public void setResourceTemplateId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tables.resource_template_id</code>.
     */
    public Long getResourceTemplateId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.tables.user_id</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tables.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.tables.is_located_in_room_ref</code>.
     */
    public void setIsLocatedInRoomRef(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tables.is_located_in_room_ref</code>.
     */
    public Integer getIsLocatedInRoomRef() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tables.shape</code>.
     */
    public void setShape(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tables.shape</code>.
     */
    public String getShape() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Long, Long, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, Long, Long, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Tables.TABLES.ID;
    }

    @Override
    public Field<String> field2() {
        return Tables.TABLES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Tables.TABLES.DESCRIPTION;
    }

    @Override
    public Field<Long> field4() {
        return Tables.TABLES.RESOURCE_TEMPLATE_ID;
    }

    @Override
    public Field<Long> field5() {
        return Tables.TABLES.USER_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Tables.TABLES.IS_LOCATED_IN_ROOM_REF;
    }

    @Override
    public Field<String> field7() {
        return Tables.TABLES.SHAPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long component4() {
        return getResourceTemplateId();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Integer component6() {
        return getIsLocatedInRoomRef();
    }

    @Override
    public String component7() {
        return getShape();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Long value4() {
        return getResourceTemplateId();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public Integer value6() {
        return getIsLocatedInRoomRef();
    }

    @Override
    public String value7() {
        return getShape();
    }

    @Override
    public TablesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TablesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TablesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TablesRecord value4(Long value) {
        setResourceTemplateId(value);
        return this;
    }

    @Override
    public TablesRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TablesRecord value6(Integer value) {
        setIsLocatedInRoomRef(value);
        return this;
    }

    @Override
    public TablesRecord value7(String value) {
        setShape(value);
        return this;
    }

    @Override
    public TablesRecord values(Long value1, String value2, String value3, Long value4, Long value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablesRecord
     */
    public TablesRecord() {
        super(Tables.TABLES);
    }

    /**
     * Create a detached, initialised TablesRecord
     */
    public TablesRecord(Long id, String name, String description, Long resourceTemplateId, Long userId, Integer isLocatedInRoomRef, String shape) {
        super(Tables.TABLES);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, resourceTemplateId);
        set(4, userId);
        set(5, isLocatedInRoomRef);
        set(6, shape);
    }
}
