/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceTemplates implements Serializable {

    private static final long serialVersionUID = 57042639;

    private Long    id;
    private String  description;
    private Boolean isPublished;
    private String  name;
    private String  tableName;
    private Long    creatorId;

    public ResourceTemplates() {}

    public ResourceTemplates(ResourceTemplates value) {
        this.id = value.id;
        this.description = value.description;
        this.isPublished = value.isPublished;
        this.name = value.name;
        this.tableName = value.tableName;
        this.creatorId = value.creatorId;
    }

    public ResourceTemplates(
        Long    id,
        String  description,
        Boolean isPublished,
        String  name,
        String  tableName,
        Long    creatorId
    ) {
        this.id = id;
        this.description = description;
        this.isPublished = isPublished;
        this.name = name;
        this.tableName = tableName;
        this.creatorId = creatorId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getIsPublished() {
        return this.isPublished;
    }

    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public Long getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ResourceTemplates (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(isPublished);
        sb.append(", ").append(name);
        sb.append(", ").append(tableName);
        sb.append(", ").append(creatorId);

        sb.append(")");
        return sb.toString();
    }
}
