/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rooms implements Serializable {

    private static final long serialVersionUID = 364754486;

    private Long    id;
    private String  name;
    private String  description;
    private Long    resourceTemplateId;
    private Long    userId;
    private String  squares;
    private Double  tables;
    private Double  todayFrom;
    private Double  todayTo;
    private String  geolocation;
    private Integer mondFrom;
    private Integer mondTo;
    private Integer square;

    public Rooms() {}

    public Rooms(Rooms value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.resourceTemplateId = value.resourceTemplateId;
        this.userId = value.userId;
        this.squares = value.squares;
        this.tables = value.tables;
        this.todayFrom = value.todayFrom;
        this.todayTo = value.todayTo;
        this.geolocation = value.geolocation;
        this.mondFrom = value.mondFrom;
        this.mondTo = value.mondTo;
        this.square = value.square;
    }

    public Rooms(
        Long    id,
        String  name,
        String  description,
        Long    resourceTemplateId,
        Long    userId,
        String  squares,
        Double  tables,
        Double  todayFrom,
        Double  todayTo,
        String  geolocation,
        Integer mondFrom,
        Integer mondTo,
        Integer square
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.resourceTemplateId = resourceTemplateId;
        this.userId = userId;
        this.squares = squares;
        this.tables = tables;
        this.todayFrom = todayFrom;
        this.todayTo = todayTo;
        this.geolocation = geolocation;
        this.mondFrom = mondFrom;
        this.mondTo = mondTo;
        this.square = square;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getResourceTemplateId() {
        return this.resourceTemplateId;
    }

    public void setResourceTemplateId(Long resourceTemplateId) {
        this.resourceTemplateId = resourceTemplateId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getSquares() {
        return this.squares;
    }

    public void setSquares(String squares) {
        this.squares = squares;
    }

    public Double getTables() {
        return this.tables;
    }

    public void setTables(Double tables) {
        this.tables = tables;
    }

    public Double getTodayFrom() {
        return this.todayFrom;
    }

    public void setTodayFrom(Double todayFrom) {
        this.todayFrom = todayFrom;
    }

    public Double getTodayTo() {
        return this.todayTo;
    }

    public void setTodayTo(Double todayTo) {
        this.todayTo = todayTo;
    }

    public String getGeolocation() {
        return this.geolocation;
    }

    public void setGeolocation(String geolocation) {
        this.geolocation = geolocation;
    }

    public Integer getMondFrom() {
        return this.mondFrom;
    }

    public void setMondFrom(Integer mondFrom) {
        this.mondFrom = mondFrom;
    }

    public Integer getMondTo() {
        return this.mondTo;
    }

    public void setMondTo(Integer mondTo) {
        this.mondTo = mondTo;
    }

    public Integer getSquare() {
        return this.square;
    }

    public void setSquare(Integer square) {
        this.square = square;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rooms (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(resourceTemplateId);
        sb.append(", ").append(userId);
        sb.append(", ").append(squares);
        sb.append(", ").append(tables);
        sb.append(", ").append(todayFrom);
        sb.append(", ").append(todayTo);
        sb.append(", ").append(geolocation);
        sb.append(", ").append(mondFrom);
        sb.append(", ").append(mondTo);
        sb.append(", ").append(square);

        sb.append(")");
        return sb.toString();
    }
}
