/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables implements Serializable {

    private static final long serialVersionUID = -651853696;

    private Long    id;
    private String  name;
    private String  description;
    private Long    resourceTemplateId;
    private Long    userId;
    private Integer isLocatedInRoomRef;
    private String  shape;

    public Tables() {}

    public Tables(Tables value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.resourceTemplateId = value.resourceTemplateId;
        this.userId = value.userId;
        this.isLocatedInRoomRef = value.isLocatedInRoomRef;
        this.shape = value.shape;
    }

    public Tables(
        Long    id,
        String  name,
        String  description,
        Long    resourceTemplateId,
        Long    userId,
        Integer isLocatedInRoomRef,
        String  shape
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.resourceTemplateId = resourceTemplateId;
        this.userId = userId;
        this.isLocatedInRoomRef = isLocatedInRoomRef;
        this.shape = shape;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getResourceTemplateId() {
        return this.resourceTemplateId;
    }

    public void setResourceTemplateId(Long resourceTemplateId) {
        this.resourceTemplateId = resourceTemplateId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getIsLocatedInRoomRef() {
        return this.isLocatedInRoomRef;
    }

    public void setIsLocatedInRoomRef(Integer isLocatedInRoomRef) {
        this.isLocatedInRoomRef = isLocatedInRoomRef;
    }

    public String getShape() {
        return this.shape;
    }

    public void setShape(String shape) {
        this.shape = shape;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tables (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(resourceTemplateId);
        sb.append(", ").append(userId);
        sb.append(", ").append(isLocatedInRoomRef);
        sb.append(", ").append(shape);

        sb.append(")");
        return sb.toString();
    }
}
