/*
 * This file is generated by jOOQ.
 */
package database.tables;


import database.Indexes;
import database.Keys;
import database.Public;
import database.tables.records.AclSidRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AclSid extends TableImpl<AclSidRecord> {

    private static final long serialVersionUID = 537136339;

    /**
     * The reference instance of <code>public.acl_sid</code>
     */
    public static final AclSid ACL_SID = new AclSid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AclSidRecord> getRecordType() {
        return AclSidRecord.class;
    }

    /**
     * The column <code>public.acl_sid.id</code>.
     */
    public final TableField<AclSidRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('acl_sid_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.acl_sid.principal</code>.
     */
    public final TableField<AclSidRecord, Boolean> PRINCIPAL = createField(DSL.name("principal"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.acl_sid.sid</code>.
     */
    public final TableField<AclSidRecord, String> SID = createField(DSL.name("sid"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>public.acl_sid</code> table reference
     */
    public AclSid() {
        this(DSL.name("acl_sid"), null);
    }

    /**
     * Create an aliased <code>public.acl_sid</code> table reference
     */
    public AclSid(String alias) {
        this(DSL.name(alias), ACL_SID);
    }

    /**
     * Create an aliased <code>public.acl_sid</code> table reference
     */
    public AclSid(Name alias) {
        this(alias, ACL_SID);
    }

    private AclSid(Name alias, Table<AclSidRecord> aliased) {
        this(alias, aliased, null);
    }

    private AclSid(Name alias, Table<AclSidRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AclSid(Table<O> child, ForeignKey<O, AclSidRecord> key) {
        super(child, key, ACL_SID);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACL_SID_PKEY, Indexes.UNIQUE_UK_1);
    }

    @Override
    public Identity<AclSidRecord, Long> getIdentity() {
        return Keys.IDENTITY_ACL_SID;
    }

    @Override
    public UniqueKey<AclSidRecord> getPrimaryKey() {
        return Keys.ACL_SID_PKEY;
    }

    @Override
    public List<UniqueKey<AclSidRecord>> getKeys() {
        return Arrays.<UniqueKey<AclSidRecord>>asList(Keys.ACL_SID_PKEY, Keys.UNIQUE_UK_1);
    }

    @Override
    public AclSid as(String alias) {
        return new AclSid(DSL.name(alias), this);
    }

    @Override
    public AclSid as(Name alias) {
        return new AclSid(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AclSid rename(String name) {
        return new AclSid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AclSid rename(Name name) {
        return new AclSid(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Boolean, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
