/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq.tables.daos;


import com.softserve.rms.jooq.tables.Tables;
import com.softserve.rms.jooq.tables.records.TablesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesDao extends DAOImpl<TablesRecord, com.softserve.rms.jooq.tables.pojos.Tables, Long> {

    /**
     * Create a new TablesDao without any configuration
     */
    public TablesDao() {
        super(Tables.TABLES, com.softserve.rms.jooq.tables.pojos.Tables.class);
    }

    /**
     * Create a new TablesDao with an attached configuration
     */
    public TablesDao(Configuration configuration) {
        super(Tables.TABLES, com.softserve.rms.jooq.tables.pojos.Tables.class, configuration);
    }

    @Override
    public Long getId(com.softserve.rms.jooq.tables.pojos.Tables object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tables.TABLES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchById(Long... values) {
        return fetch(Tables.TABLES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.softserve.rms.jooq.tables.pojos.Tables fetchOneById(Long value) {
        return fetchOne(Tables.TABLES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tables.TABLES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByName(String... values) {
        return fetch(Tables.TABLES.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tables.TABLES.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByDescription(String... values) {
        return fetch(Tables.TABLES.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>resource_template_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfResourceTemplateId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tables.TABLES.RESOURCE_TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resource_template_id IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByResourceTemplateId(Long... values) {
        return fetch(Tables.TABLES.RESOURCE_TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Tables.TABLES.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByUserId(Long... values) {
        return fetch(Tables.TABLES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_located_in_room_ref BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfIsLocatedInRoomRef(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Tables.TABLES.IS_LOCATED_IN_ROOM_REF, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_located_in_room_ref IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByIsLocatedInRoomRef(Integer... values) {
        return fetch(Tables.TABLES.IS_LOCATED_IN_ROOM_REF, values);
    }

    /**
     * Fetch records that have <code>shape BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchRangeOfShape(String lowerInclusive, String upperInclusive) {
        return fetchRange(Tables.TABLES.SHAPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>shape IN (values)</code>
     */
    public List<com.softserve.rms.jooq.tables.pojos.Tables> fetchByShape(String... values) {
        return fetch(Tables.TABLES.SHAPE, values);
    }
}
