/*
 * This file is generated by jOOQ.
 */
package database.tables.daos;


import database.tables.ResourceRelations;
import database.tables.records.ResourceRelationsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceRelationsDao extends DAOImpl<ResourceRelationsRecord, database.tables.pojos.ResourceRelations, Long> {

    /**
     * Create a new ResourceRelationsDao without any configuration
     */
    public ResourceRelationsDao() {
        super(ResourceRelations.RESOURCE_RELATIONS, database.tables.pojos.ResourceRelations.class);
    }

    /**
     * Create a new ResourceRelationsDao with an attached configuration
     */
    public ResourceRelationsDao(Configuration configuration) {
        super(ResourceRelations.RESOURCE_RELATIONS, database.tables.pojos.ResourceRelations.class, configuration);
    }

    @Override
    public Long getId(database.tables.pojos.ResourceRelations object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ResourceRelations.RESOURCE_RELATIONS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchById(Long... values) {
        return fetch(ResourceRelations.RESOURCE_RELATIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public database.tables.pojos.ResourceRelations fetchOneById(Long value) {
        return fetchOne(ResourceRelations.RESOURCE_RELATIONS.ID, value);
    }

    /**
     * Fetch records that have <code>related_resource_template_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchRangeOfRelatedResourceTemplateId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ResourceRelations.RESOURCE_RELATIONS.RELATED_RESOURCE_TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>related_resource_template_id IN (values)</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchByRelatedResourceTemplateId(Long... values) {
        return fetch(ResourceRelations.RESOURCE_RELATIONS.RELATED_RESOURCE_TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>resource_parameter_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchRangeOfResourceParameterId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ResourceRelations.RESOURCE_RELATIONS.RESOURCE_PARAMETER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resource_parameter_id IN (values)</code>
     */
    public List<database.tables.pojos.ResourceRelations> fetchByResourceParameterId(Long... values) {
        return fetch(ResourceRelations.RESOURCE_RELATIONS.RESOURCE_PARAMETER_ID, values);
    }
}
