/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceRelations implements Serializable {

    private static final long serialVersionUID = 1940577132;

    private Long id;
    private Long relatedResourceTemplateId;
    private Long resourceParameterId;

    public ResourceRelations() {}

    public ResourceRelations(ResourceRelations value) {
        this.id = value.id;
        this.relatedResourceTemplateId = value.relatedResourceTemplateId;
        this.resourceParameterId = value.resourceParameterId;
    }

    public ResourceRelations(
        Long id,
        Long relatedResourceTemplateId,
        Long resourceParameterId
    ) {
        this.id = id;
        this.relatedResourceTemplateId = relatedResourceTemplateId;
        this.resourceParameterId = resourceParameterId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRelatedResourceTemplateId() {
        return this.relatedResourceTemplateId;
    }

    public void setRelatedResourceTemplateId(Long relatedResourceTemplateId) {
        this.relatedResourceTemplateId = relatedResourceTemplateId;
    }

    public Long getResourceParameterId() {
        return this.resourceParameterId;
    }

    public void setResourceParameterId(Long resourceParameterId) {
        this.resourceParameterId = resourceParameterId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ResourceRelations (");

        sb.append(id);
        sb.append(", ").append(relatedResourceTemplateId);
        sb.append(", ").append(resourceParameterId);

        sb.append(")");
        return sb.toString();
    }
}
