/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S3bucketTest implements Serializable {

    private static final long serialVersionUID = 110732486;

    private Long   id;
    private String fileName;
    private String resourceName;

    public S3bucketTest() {}

    public S3bucketTest(S3bucketTest value) {
        this.id = value.id;
        this.fileName = value.fileName;
        this.resourceName = value.resourceName;
    }

    public S3bucketTest(
        Long   id,
        String fileName,
        String resourceName
    ) {
        this.id = id;
        this.fileName = fileName;
        this.resourceName = resourceName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getResourceName() {
        return this.resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S3bucketTest (");

        sb.append(id);
        sb.append(", ").append(fileName);
        sb.append(", ").append(resourceName);

        sb.append(")");
        return sb.toString();
    }
}
