/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 634130865;

    private Long    id;
    private String  email;
    private Boolean enabled;
    private String  firstName;
    private String  lastName;
    private String  password;
    private String  phone;
    private Long    roleId;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.email = value.email;
        this.enabled = value.enabled;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.password = value.password;
        this.phone = value.phone;
        this.roleId = value.roleId;
    }

    public Users(
        Long    id,
        String  email,
        Boolean enabled,
        String  firstName,
        String  lastName,
        String  password,
        String  phone,
        Long    roleId
    ) {
        this.id = id;
        this.email = email;
        this.enabled = enabled;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.phone = phone;
        this.roleId = roleId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(enabled);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(password);
        sb.append(", ").append(phone);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
