/*
 * This file is generated by jOOQ.
 */
package com.softserve.rms.jooq;


import com.softserve.rms.jooq.tables.AclClass;
import com.softserve.rms.jooq.tables.AclEntry;
import com.softserve.rms.jooq.tables.AclObjectIdentity;
import com.softserve.rms.jooq.tables.AclSid;
import com.softserve.rms.jooq.tables.ResourceParameters;
import com.softserve.rms.jooq.tables.ResourceRelations;
import com.softserve.rms.jooq.tables.ResourceTemplates;
import com.softserve.rms.jooq.tables.Roles;
import com.softserve.rms.jooq.tables.S3bucketTest;
import com.softserve.rms.jooq.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1068100220;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.acl_class</code>.
     */
    public final AclClass ACL_CLASS = com.softserve.rms.jooq.tables.AclClass.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public final AclEntry ACL_ENTRY = com.softserve.rms.jooq.tables.AclEntry.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public final AclObjectIdentity ACL_OBJECT_IDENTITY = com.softserve.rms.jooq.tables.AclObjectIdentity.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public final AclSid ACL_SID = com.softserve.rms.jooq.tables.AclSid.ACL_SID;

    /**
     * The table <code>public.resource_parameters</code>.
     */
    public final ResourceParameters RESOURCE_PARAMETERS = com.softserve.rms.jooq.tables.ResourceParameters.RESOURCE_PARAMETERS;

    /**
     * The table <code>public.resource_relations</code>.
     */
    public final ResourceRelations RESOURCE_RELATIONS = com.softserve.rms.jooq.tables.ResourceRelations.RESOURCE_RELATIONS;

    /**
     * The table <code>public.resource_templates</code>.
     */
    public final ResourceTemplates RESOURCE_TEMPLATES = com.softserve.rms.jooq.tables.ResourceTemplates.RESOURCE_TEMPLATES;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = com.softserve.rms.jooq.tables.Roles.ROLES;

    /**
     * The table <code>public.s3bucket_test</code>.
     */
    public final S3bucketTest S3BUCKET_TEST = com.softserve.rms.jooq.tables.S3bucketTest.S3BUCKET_TEST;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.softserve.rms.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACL_CLASS_ID_SEQ,
            Sequences.ACL_ENTRY_ID_SEQ,
            Sequences.ACL_OBJECT_IDENTITY_ID_SEQ,
            Sequences.ACL_SID_ID_SEQ,
            Sequences.RESOURCE_PARAMETERS_ID_SEQ,
            Sequences.RESOURCE_RELATIONS_ID_SEQ,
            Sequences.RESOURCE_TEMPLATES_ID_SEQ,
            Sequences.S3BUCKET_TEST_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AclClass.ACL_CLASS,
            AclEntry.ACL_ENTRY,
            AclObjectIdentity.ACL_OBJECT_IDENTITY,
            AclSid.ACL_SID,
            ResourceParameters.RESOURCE_PARAMETERS,
            ResourceRelations.RESOURCE_RELATIONS,
            ResourceTemplates.RESOURCE_TEMPLATES,
            Roles.ROLES,
            S3bucketTest.S3BUCKET_TEST,
            Users.USERS);
    }
}
